name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Lint
        uses: j2kun/chktex-action@v2
        with:
          lint-all: true
      - name: fetch template
        run: |
          wget https://github.com/TheDreadClimber/ClimbingBookTemplate/archive/refs/heads/main.zip
          unzip main.zip
      - name: prepare template
        run: |
          cp -r src/* ClimbingBookTemplate-main/
          rm -rf ClimbingBookTemplate-main/test
          #cd ClimbingBookTemplate-main
          # Full
          # cd Full
          # Chaney
          # cd Chaney
          # KY Boulder
          #cd KYBoulder
          #cp _intro.tex ../Introduction.tex
          #cp _config.tex ../config.tex
          #cp _chapters.tex ../chapters.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: ClimbingBookTemplate-main/src/main.tex
        env:
          TEXINPUTS: ".:./ClimbingBookTemplate-main//:"
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
