name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Lint
        uses: j2kun/chktex-action@v2
        with:
          lint-all: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: src/main.tex
        env:
          TEXINPUTS: ".:./src:./test//:"
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
